runtime: nodejs16

service: default
env_variables:
  NODE_ENV: production
  SERVER_PORT: 8080
  XFROM: dawProyectXFROM
  DDBB_USER: root
  DDBB_NAME: proyecto_fp
  DDBB_PASSWORD: nuncamais
  DDBB_SOCKEPATCH: /cloudsql/daw-project-381621:europe-west1:daw-project-instance

handlers:
  - url: /.*
    script: auto
  